config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'schools#index'
  # get 'top', :to => 'main#home'
  # get 'func', :to => 'common#common_func'
  resources :schools
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
      else
        can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/school.rb
class School < ActiveRecord::Base
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/common_controller.rb
class CommonController < ApplicationController
  
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    
  end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_filter :authenticate_user!
  def index
    @schools = School.all
  end

  def new
    @school = School.new
  end

  def create
    @school = School.new(school_params)
    @school.save
    redirect_to schools_path
  end

  def edit
    @school = School.find(params[:id])
  end

  def show
    Rails.logger.debug(params[:id])
    @school = School.find(params[:id])
  end

  def update
    @school = School.find(params[:id])
    @school.update(school_params)
    redirect_to schools_path
  end

  def destroy
    @school = School.find(params[:id])
    @school.destroy
    redirect_to schools_path
  end
  
  private
    def school_params
      params.require(:school).permit(:name, :age)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/common/common_func.html.erb
agwedhsgerih

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RoRLearning</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if user_signed_in? %>
  Signed in as <%= current_user.email %>. Not you?
  <%= link_to "Edit profile", edit_user_registration_path %>
  <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
<% end %>

<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, id: "flash_#{name}" %>
<% end %>
<br/>
<%= yield %>

</body>
</html>

app/views/main/_index.html.erb
render from main/index

app/views/main/home.html.erb
this is home page

app/views/main/index.html.erb
main index

app/views/schools/_form.html.erb
<%= form_for @school do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_area :name %>
  </p>
 
  <p>
    <%= f.label :age %>
    <%= f.text_field :age %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to "Cancel", schools_path%>

app/views/schools/edit.html.erb
<%= render "form" %>

app/views/schools/index.html.erb
<%= link_to "Add", new_school_path %>
<table id="tbl-school" border="1">
  <tr>
    <th>Name</th>
    <th>Age</th>
  </tr>
  <% @schools.each do |school| %>
    <tr>
      <td><%= school.name %></td>
      <td><div class="age" style="display: block;"><%= school.age %></div></td>
      <td><button type="button" class="show-age">Show age</td>
      <td><%= link_to "View", school_path(school.id) %></td>
      <td><%= link_to "Edit", edit_school_path(school.id) %></td>
      <td><%= link_to "Delete", school_path(school.id), method: :DELETE %></td>
    </tr>
  <% end %>
</table>

<button type="button" id="btn-change-all">Change all

app/views/schools/new.html.erb
<%= render "form" %>

app/views/schools/show.html.erb
<%= @school.name %> is <%= @school.age %> years old
<%= link_to "Back", schools_path%>